blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('edit_blog/<slug:slug>/', views.edit_blog, name='edit_blog'),
    path('delete_blog/<slug:slug>/', views.delete_blog, name='delete_blog'),
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
]

wrottesley_golf_club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('memberships/', include('memberships.urls')),
    path('tournaments/', include('tournaments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Blog(models.Model):

    class Meta:
        ordering = ['-date_created']

    author = models.ForeignKey(User, on_delete=models.SET_NULL,
                               null=True,
                               blank=True,
                               related_name='blog_posts'
                               )
    slug = models.SlugField(max_length=200, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    main_image = models.ImageField(null=False, blank=False)
    title = models.CharField(max_length=300,
                             unique=True,
                             null=False,
                             blank=False,
                             )
    sub_title_one = models.CharField(max_length=300,
                                     unique=True,
                                     null=False,
                                     blank=False,
                                     )
    blog_content_one = models.TextField(null=False, blank=False,)
    sub_title_two = models.CharField(max_length=300, default='', blank=True,)
    blog_content_two = models.TextField(default='', blank=True,)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("blog_detail", kwargs={"slug": str(self.slug)})


class Comment(models.Model):

    class Meta:
        ordering = ['-date_created']

    blog = models.ForeignKey(Blog,
                             on_delete=models.CASCADE,
                             related_name='comments'
                             )
    name = models.OneToOneField(to=User, on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Blog, Comment


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('slug', 'title', 'main_image',
                  'sub_title_one', 'blog_content_one',
                  'sub_title_two', 'blog_content_two')

    main_image = (
        forms.ImageField(
            label="Main Image",
            required=True,
            widget=CustomClearableFileInput
        )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['slug'].widget.attrs['placeholder'] = (
            'e.g title-of-your-blog'
        )

        self.fields['title'].widget.attrs['placeholder'] = (
            'Title of your blog post'
        )

        self.fields['sub_title_one'].widget.attrs['placeholder'] = (
            'First subheading'
        )

        self.fields['blog_content_one'].widget.attrs['placeholder'] = (
            'First paragraph of your blog'
        )

        self.fields['sub_title_two'].widget.attrs['placeholder'] = (
            'Second subheading'
        )

        self.fields['blog_content_two'].widget.attrs['placeholder'] = (
            'Second paragraph of your blog'
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

    body = forms.CharField(label="")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['body'].widget.attrs['placeholder'] = 'Add a comment...'

blog/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Blog
from .forms import BlogPostForm, CommentForm

# Create your views here.


def blog_list(request):
    """
    A view to return all the blog posts
    """
    all_blog_posts = Blog.objects.all().order_by('-date_created')

    context = {
        'all_blog_posts': all_blog_posts,
        'on_blog_page': True
    }

    return render(request, 'blog/blog.html', context)


def blog_detail(request, slug):
    """ A view to show the individual blog post """
    blog_post = get_object_or_404(Blog, slug=slug)
    comments = (
        blog_post.comments.filter(approved=True).order_by("-date_created")
    )
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.blog = blog_post
            # Add the username to the comment
            new_comment.name = request.user
            # Save the comment to the database
            new_comment.save()
            # Show message to confirm comment
            messages.success(
                request,
                'Thank you for your comment, it has been sent \
                    for approval and will appear once done'
            )
            return redirect(reverse('blog_detail', args=[blog_post.slug]))
    else:
        comment_form = CommentForm()

    context = {
        'blog_post': blog_post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'on_blog_page': True
    }

    return render(request, 'blog/blog_detail.html', context)


@login_required
def add_blog(request):
    """ A view to add a new blog post """
    if not request.user.is_superuser:
        messages.error(request, 'Only WGC staff can do this"')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            blog_post = form.save()
            messages.success(
                request, f'New post: {blog_post.title} uploaded successfully'
            )
            new_blog = get_object_or_404(Blog, slug=blog_post.slug)
            new_blog.author = request.user
            new_blog.save()
            return redirect(reverse('blog_detail', args=[blog_post.slug]))
        else:
            messages.error(request, 'There was an error. Please try again')
    else:
        form = BlogPostForm()

    context = {
        'form': form,
        'on_blog_page': True
    }

    return render(request, 'blog/add_new_blog.html', context)


@login_required
def edit_blog(request, slug):
    """ A view to edit a blog post """
    if not request.user.is_superuser:
        messages.error(request, 'Only WGC staff can do this"')
        return redirect(reverse('home'))

    blog_post = get_object_or_404(Blog, slug=slug)
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES, instance=blog_post)
        if form.is_valid():
            form.save()
            messages.success(request, f'{blog_post.title} updated')
            return redirect(reverse('blog_detail', args=[blog_post.slug]))
        else:
            messages.error(request, 'There was an error. Please try again')
    else:
        form = BlogPostForm(instance=blog_post)
        messages.info(request, f'Now editing {blog_post.title}')

    context = {
        'form': form,
        'blog_post': blog_post,
        'on_blog_page': True
    }

    return render(request, 'blog/edit_blog.html', context)


@login_required
def delete_blog(request, slug):
    """ Delete a blog post """
    if not request.user.is_superuser:
        messages.error(request, 'Only WGC staff can do this"')
        return redirect(reverse('home'))

    blog_post = get_object_or_404(Blog, slug=slug)
    blog_post.delete()
    messages.success(request, f'{blog_post.title} deleted')
    return redirect(reverse('blog_list'))

blog/templates/blog/add_new_blog.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5">
            <h1 class="libre">Add New Blog</h1>
            <hr>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
            <form action="{% url 'add_blog' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'main_image' %}
                {{ field|as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <button class="btn primary-btn-lg" type="submit">Add Blog</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('.new-image').change(function () {
        var file = $('.new-image')[0].files[0];
        $('#filename').text(`Your chosen image is: ${file.name}`)
    });
</script>
{% endblock postloadjs %}

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5">
            <h1 class="libre">Blog</h1>
            <hr>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
            {% for post in all_blog_posts %}
            <div class="card mb-3">
                <img class="card-img-top blog-post-main-image" src="{{ MEDIA_URL }}{{ post.main_image }}"
                    alt="{{ post.title }} image">
                <div class="card-body">
                    <h2 class="blog-card-title libre">{{ post.title }}</h2>
                    <p class="small">A blog post by {{ post.author }}</p>
                    <p class="card-text">{{ post.blog_content_one|slice:":200" }}...</p>
                    <a href="{% url 'blog_detail' post.slug  %}" class="btn primary-btn-lg">Read More</a>
                    <p class="card-text">
                        <small class="text-muted">Last updated on {{ post.last_updated }}</small>
                        {% if request.user.is_superuser %}
                        <small class="text-muted float-right">
                            <a class="green" href="{% url 'edit_blog' post.slug %}">
                                <i class="fas fa-edit"></i> EDIT
                            </a> |
                            <a class="red" href="{% url 'delete_blog' post.slug %}">
                                <i class="fas fa-trash-alt"></i> DELETE
                            </a>
                        </small>
                        {% endif %}
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% if request.user.is_superuser %}
<div>
    <a class="p-0 add_blog_btn" href="{% url 'add_blog' %}">
        <i class="fas fa-plus-circle p-3"></i>
    </a>
</div>
{% endif %}
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 p-0 blog-header">
            <img class="w-100 blog-header-main-image" src="{{ MEDIA_URL }}{{ blog_post.main_image }}"
                alt="Card image cap">
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3">
            <div class="col-12 text-center">
                <h1 class="libre mt-5">{{ blog_post.title }}</h1>
            </div>
            <div class="col">
                <p class="mt-5">
                    A blog post by {{ blog_post.author }}
                    <span class="float-right">
                        <i class="fas fa-comment-alt"></i> {{ comments|length }}
                    </span>
                </p>
                <hr>
            </div>
            <div class="card-body blog-text">
                <p class="blog_subtitle libre">{{ blog_post.sub_title_one }}</p>
                <p class="card-text">{{ blog_post.blog_content_one|linebreaksbr }}</p>
                <br>
                {% if blog_post.sub_title_two %}
                <p class="blog_subtitle libre">{{ blog_post.sub_title_two }}</p>
                <p class="card-text">{{ blog_post.blog_content_two|linebreaksbr }}</p>
                {% endif %}
                <p class="card-text">
                    <small class="text-muted">Last updated on {{ blog_post.last_updated }}</small>
                    {% if request.user.is_superuser %}
                    <small class="text-muted float-right">
                        <a href="{% url 'edit_blog' blog_post.slug %}">
                            <i class="fas fa-edit"></i> EDIT
                        </a> |
                        <a class="red" href="{% url 'delete_blog' blog_post.slug %}">
                            <i class="fas fa-trash-alt"></i> DELETE
                        </a>
                    </small>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-6 offset-lg-3 mt-5">
            {% if comments|length == 1 %}
            <p class="text-center"><strong>{{ comments|length }} COMMENT</strong></p>
            {% else %}
            <p class="text-center"><strong>{{ comments|length }} COMMENTS</strong></p>
            {% endif %}
            <hr>
            {% if request.user.is_authenticated %}
            <div class="card-body">
                <h5>Leave a comment</h5>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form|crispy }}
                    {% csrf_token %}
                    <small class="float-right" id="character-count"><span id="char">0</span> / 200</small>
                    <br>
                    <button type="submit" class="btn primary-btn-lg">
                        <i class="fas fa-comment-alt"></i> Post Comment
                    </button>
                </form>
            </div>
            {% else %}
            <div class="col-12 col-lg-6 offset-lg-3">
                <div class="card-body">
                    <p class="libre"><a href="{% url 'account_login' %}">Login</a> to leave a comment</p>
                </div>
            </div>
            {% endif %}
            {% if comments %}
            {% for comment in comments %}
            <div class="comments" style="padding: 1.25em;">
                <p class="font-weight-bold">
                    {{ comment.name }}
                    <span class=" text-muted font-weight-normal">
                        {{ comment.date_created }}
                    </span>
                </p>
                "{{ comment.body | linebreaks }}"
            </div>
            <br>
            {% endfor %}
            {% else %}
            <div class="comments" style="padding: 10px;">
                <p class="font-weight-bold">
                    <i class="fas fa-comment-alt"></i> No comments yet. Be the first to comment!
                </p>
            </div>
            <hr>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#id_body').keyup(function () {
        var maxLength = 800;
        var currentLegnth = $('#id_body').val().length;
        var char = $('#char');
        var submit = $(":submit");
        var characterCount = $('#character-count');
        char.text(currentLegnth);
        if (currentLegnth > 200) {
            characterCount.css('color', '#f2542d');
            characterCount.css('font-weight', 'bold');
            submit.prop('disabled', true);
        } else if (currentLegnth >= 140 && currentLegnth <= 200) {
            characterCount.css('color', '#F26716');
            characterCount.css('font-weight', 'bold');
            submit.prop('disabled', false);
        } else {
            characterCount.css('color', '#127475');
            characterCount.css('font-weight', 'normal');
            submit.prop('disabled', false);
        }
    });
</script>
{% endblock postloadjs %}

blog/templates/blog/edit_blog.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5">
            <h1 class="libre">Edit Blog</h1>
            <hr>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
            <form action="{% url 'edit_blog' blog_post.slug %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'main_image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <a class="btn secondary-btn" href="{% url 'blog_detail' blog_post.slug %}">Cancel</a>
                <button class="btn primary-btn-lg" type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('.new-image').change(function () {
        var file = $('.new-image')[0].files[0];
        $('#filename').text(`Your chosen image is: ${file.name}`)
    });
</script>
{% endblock postloadjs %}